language: python
python:
- 2.7
- 3.5
install:
- pip install future
- pip install nose
- pip install flake8
- pip install coveralls
script:
- flake8 --ignore=F401 gatilegrid tests
- coverage run --source=gatilegrid setup.py test
- coverage report -m
after_success: coveralls
deploy:
  provider: pypi
  user: loicgasser
  password:
    secure: eTPTSibyCFeFUiBU/8RoFH80tgpd7JIuKOAcTatJK9KoMwtDVIeW8Eylz58/ifzOWQxim+i9JmmujAMOPTUhVTwaQBkWbgeE12PXwf3zn3sGQYq1sE53/EtKMKlkVATTzlVXnzvQmH+lPw6HFL7GgBDDN6SmiNF1T3/MrnsqsbHo/bBfWIiHSahef9E2Sqj3KVrkKZgwIl2QDBM/WWXatQWwS087scpR9uMHtyWEScyuHWx/7JmGfF2CLtokOOVtEgI1Nt9LwkpppIIX8NnepavYY/H2TKcDYJswVNI49a4XUVDSvZNbh08sXx2aoKWpsCiS8e3UxOLaXJ6oLCi76+DDlM7rUm3hkiHugY49RX6pztuhTEBcYvP6NcTTtajdw/9AN7vCHOEbP+Ys/3yqovsFDN7pEY7bNFLQvFPKiRvhlGP1yxb0ZzYYZZSyJLF1K0f4TqMS2kXf+9jqArOF9sdwHHWDLILAwtrb6DW0tF3S3Adn7Bx3zbhJjORqxGr5E9+WhgezrgmsM/cN+XXYbn3HG9Ijm1eTfDUiBjJ6KxLc06Jm9zAk4kWFYEqHyYDoz4bR+MrDRaRBDcdxhneLOFHhe9v/e38lNsOiblWbwippQOUKHZtOOm7s1+4gbwguj78R2UZOLHgw+aXc/8qAaqGu3OUZMaU0LzgMdnmkmfY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: geoadmin/gatilegrid
