language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8
install:
- pip install future
- pip install nose
- pip install flake8
- pip install coveralls
script:
- flake8 --ignore=F401 gatilegrid tests
- coverage run --source=gatilegrid setup.py test
- coverage report -m
