version: 0.2

env:
  shell: bash
  variables:
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update -qq
      - apt-get install -yqq python3-pip python3.8 python3.9

  build:
    commands:
      - python --version
      - python -m pip install -qq flake8 future nose coveralls
      - echo "Runs flake8..."
      - python -m flake8 --ignore=F401 gatilegrid tests
      - echo "Runs coverage"
      - python -m coverage run --source=gatilegrid setup.py test
      - python -m coverage report -m
      - python3.8 --version
      - python3.8 -m pip install -qq flake8 future nose coveralls
      - echo "Runs flake8..."
      - python3.8 -m flake8 --ignore=F401 gatilegrid tests
      - echo "Runs coverage"
      - python3.8 -m coverage run --source=gatilegrid setup.py test
      - python3.8 -m coverage report -m
      - python3.9 --version
      - python3.9 -m pip install -qq flake8 future nose coveralls
      - echo "Runs flake8..."
      - python3.9 -m flake8 --ignore=F401 gatilegrid tests
      - echo "Runs coverage"
      - python3.9 -m coverage run --source=gatilegrid setup.py test
      - python3.9 -m coverage report -m
