version: 0.2

env:
  shell: bash
  variables:
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update -qq
      - apt-get install -yqq python3-pip python3.7 python3.8

  build:
    commands:
      - |
      - python -m pip install -qq flake8 nose coveralls tox
      # tox
      - echo "Runs tox..."
      - python -m tox
